services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INIT_ROOT_USERNAME: development
      MONGO_INIT_ROOT_PASSWORD: testpassword
  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGO_INIT_ROOT_USERNAME: development
      ME_MONGO_INIT_ROOT_PASSWORD: development
      ME_CONFIG_MONGODB_URL: mongodb://development:testpassword@mongo:27017/
